//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> SubcategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public double Quantity { get; set; }
        public string Unit { get; set; }
    
        public virtual Subcategories Subcategories { get; set; }
    }
}
